### ISSUE TITLE
Add a way to periodically flush

### ISSUE THREAD

**Issue by crccheck** [voldern/kinesis-write-stream#4]
Hi, the stream I'm putting into this sometimes trickles. So I'm looking for a way to batch more on a time basis rather than `highWaterMark`. I tried modifying the existing code but didn't get anything that worked. Would switching to `cork`/`uncork` be a more generic way to buffer writes?

* cork https://nodejs.org/api/stream.html#stream_writable_cork
* uncork https://nodejs.org/api/stream.html#stream_writable_uncork

**Comment by crccheck** [comment]
I did an investigation and cork/uncork are close... but no cigar. The problem I ran into was I couldn't inspect new data coming in to tell when I should `uncork` and do a write. So close...

**Comment by voldern** [comment]
Hi! Thanks for creating this issue. Sorry for the slow reply, I've taken a long Easter break. 

Could setting a timeout that also flushes the queue, as is done in [voldern/elasticsearch-writable-stream#flushing](https://github.com/voldern/elasticsearch-writable-stream#flushing) be a good way to solve this?

If so I can whip up something during the middle of next week.

**Comment by crccheck** [comment]
I gave it a shot too, but with a **very big** diff https://github.com/voldern/kinesis-write-stream/compare/master...crccheck:rewrite

The API is basically the same, but the structure is drastically different so it's not exactly apples to apples

**Comment by indieisaconcept** [comment]
I've just hit this too :-) when testing a scenario with very few items. A timeout would be perfect.

**Comment by voldern** [comment]
Hi, sorry for not responding sooner! :hurtrealbad: 

Thank you for taking the time to looking into it @crccheck. I decided to merge the PR from @indieisaconcept since its introducing a lot less changes.

v1.1.0 is now on NPM with support for periodically flushing.

**Comment by indieisaconcept** [comment]
Thanks @voldern
